name: NPM Publish
description: Github action to publish to npm as part of a github workflow for NodeJS projects
inputs:
  npm-token:
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: https://registry.npmjs.org
    - name: Install dependencies
      shell: bash
      run: npm ci
    - name: Build
      shell: bash
      run: npm run build
    - name: Publish to NPM
      shell: bash
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ github.token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
