name: Snyk Test
description: Github action to execute Snyk test as part of a github workflow for NodeJS projects
inputs:
  token:
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: https://registry.npmjs.org
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Run Snyk Code Test
      uses: ./src/github-actions/code-analysis/base/snyk/code-test/node
      with:
        token: ${{ inputs.token }}