name: Deploy Storybook to Github Pages
description: Github action to deploy storybook to github pages as part of a github workflow for NodeJS projects
inputs:
  path:
    required: false
  install:
    required: false
  build:
    required: false
outputs:
  page_url:
    description: The URL of the page
    value: ${{ steps.deploy.outputs.page_url }}
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: https://registry.npmjs.org
    - id: deploy
      name: Deploy Storybook to Github Pages
      uses: ./src/github-actions/deploy/github-pages/base
      with:
        path: storybook-static
        install: npm ci
        build: npm run build-storybook