name: CI
on:
  push:
    branches: [main]
jobs:
  ci:
    permissions:
      security-events: write
      contents: write
      id-token: write
      #pages: write
    uses: ./.github/workflows/node.yml
    with:
      suppression: true
      publish: npm
    secrets: 
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}