name: Code Analysis
on:
  push:
    branches: [main]
jobs:
  code-analysis:
    permissions:
      actions: read
      security-events: write
    uses: ./.github/workflows/node.yml
    with:
      suppression: true
      publish: npm
    secrets: 
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}