name: CI
on:
  push:
    branches: [main]
jobs:
  ci:
    permissions:
      #actions: read
      security-events: write
      contents: write
      #issues: write
      #pull-requests: write
      id-token: write
      pages: write # TODO split workflows and dont require this
    uses: ./.github/workflows/node.yml
    with:
      suppression: true
      publish: npm
    secrets: 
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}