name: CI
on:
  push:
    branches: [main]
jobs:
  ci:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/node.yml
    with:
      suppression: true
      publish: npm
    secrets: 
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}