name: Code Analysis
on:
  push:
    branches: [main]
jobs:
  code-analysis:
    permissions:
      actions: read
      security-events: write
    uses: ./.github/workflows/node.yml
    with:
      project: Tarsilla - Commit Wizard
      suppression: suppressions.xml