name: CI/CD
on:
  push:
    branches: [main]
jobs:
  ci-cd:
    permissions:
      security-events: write
      contents: write
      id-token: write
    uses: tarsilla-app/workflows/.github/workflows/node.yml@main
    with:
      code-analysis: |
        {
          "snyk": ["test", "code-test"],
          "owasp": {
            "suppression": true,
          },
          "codeql": true
        }
      publish: |
        {
          "npm": true
        }
    secrets: 
      snyk-token: ${{ secrets.SNYK_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}