name: 'NodeJS Code Analysis'
description: 'Github workflow to execute code analysis as part of a github workflow for NodeJS projects'
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      args:
        required: false
        type: string
jobs:
  owasp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: ./src/github-actions/code-analysis/node/owasp
        with:
          project: ${{ inputs.project }}
          args: ${{ inputs.args }}
  codeql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CodeQL Analysis
        uses: ./src/github-actions/code-analysis/node/codeql
        with:
          language: javascript-typescript
          build-mode: none
