name: NodeJS Code Analysis
description: Github workflow to execute code analysis as part of a github workflow for NodeJS projects
on:
  workflow_call:
    inputs:
      suppression:
        required: false
        type: boolean
    secrets:
      token:
        required: true
jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run OWASP Dependency-Check
        uses: ./src/github-actions/code-analysis/node/snyk-test
        with:
          token: ${{ secrets.token }}
  owasp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run OWASP Dependency-Check
        uses: ./src/github-actions/code-analysis/node/owasp
        with:
          suppression: ${{ inputs.suppression }}
  snyk-code-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run OWASP Dependency-Check
        uses: ./src/github-actions/code-analysis/node/snyk-code-test
        with:
          token: ${{ secrets.token }}
  codeql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run CodeQL Analysis
        uses: ./src/github-actions/code-analysis/node/codeql