name: 'NodeJS Code Analysis'
description: 'Github workflow to execute code analysis as part of a github workflow for NodeJS projects'
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      args:
        required: false
        type: string
jobs:
  owasp:
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP Dependency-Check
        uses: ./owasp
        with:
          project: ${{ inputs.project }}
          args: ${{ inputs.args }}
  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
    steps:
      - name: Run CodeQL Analysis
        uses: ./codeql
        with:
          language: javascript-typescript
          build-mode: none
