name: NodeJS CI
description: Github workflow to execute ci as part of a github workflow for NodeJS projects
on:
  workflow_call:
    inputs:
      local-actions:
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: false
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish to NPM
        if: ${{ inputs.local-actions }}
        uses: ./src/github-actions/publish/npm
        with:
          token: ${{ secrets.token }}
      - name: Publish to NPM
        if: ${{ !inputs.local-actions }}
        uses: tarsilla-app/commit-wizard/src/github-actions/publish/npm@main
        with:
          token: ${{ secrets.token }}