name: NodeJS CI
description: Github workflow to execute ci as part of a github workflow for NodeJS projects
on:
  workflow_call:
    inputs:
      local-actions:
        required: false
        type: boolean
        default: false
      suppression:
        required: false
        type: boolean
        default: false
jobs:
  owasp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run OWASP Dependency-Check
        if: ${{ inputs.local-actions }}
        uses: ./src/github-actions/code-analysis/node/owasp
        with:
          suppression: ${{ inputs.suppression }}
      - name: Run OWASP Dependency-Check
        if: ${{ !inputs.local-actions }}
        uses: tarsilla-app/commit-wizard/src/github-actions/code-analysis/node/owasp@main
        with:
          suppression: ${{ inputs.suppression }}