name: NodeJS CI
description: Github workflow to execute ci as part of a github workflow for NodeJS projects
on:
  workflow_call:
jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy Storybook to Github Pages
        uses: ./src/github-actions/deploy/github-pages/storybook